server:
  servlet:
    context-path: /
  port: 9999

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://122.51.55.27:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 960426daxi
  redis:
    database: 0
    host: 122.51.55.27
    port: 6379
    password: joe666
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 5000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
#    show-sql: true