spring:
  redis:
    database: 0
    host: 122.51.55.27
    port: 6379
    password: joe666
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 5000